name = "Antistasi Loot to Vehicle Extended";
logo = "\LootToVehicleExtended\ui\bear_ca.paa";
logoOver = "\LootToVehicleExtended\ui\bear_over_ca.paa";
overviewPicture = "\LootToVehicleExtended\ui\bear_ca.paa";
picture = "\LootToVehicleExtended\ui\antistasi_looter_co.paa";
action = "http://teamonetactical.com";
hidePicture = 0;
hideName = 0;
overview = "Loot to Vehicle for ACE and Antistasi Extended";